blank_issues_enabled: false
contact_links:
  - name: IDL for VSCode Community Support
    url: https://github.com/interactive-data-language/vscode-idl/discussions
    about: Please ask and answer questions here.